### PR TITLE
Translated line height and description

### PR DESCRIPTION
**Pull request by comcloudway**

### CODE REVIEW

**Comment by comcloudway** [comment]
@adil192 I just noticed an embarrassing mistake - it was supposed to say `Zeilenhöhe` (notice the `n` in the middle).
Can you fix this? I not quite sure how to

**Comment by adil192** [comment]
> `Zeilenhöhe`

Fixed in https://github.com/adil192/saber/commit/095ef68f33abdc91529960fd4091d2af5b8ea47d

**Comment by adil192** [comment]
Hi @comcloudway, would you be interested in being @'ed when there's new strings that need to be translated? https://github.com/adil192/saber/issues/19#issuecomment-1306096416

**Comment by comcloudway** [comment]
Yeah, why not :shrug: 

I can't promise anything but I'll try to stay up to date.

**Pull request merged**
