### PR TITLE
snap: use temporary branch for fixed metadata

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Comment by adil192** [comment]
Is the plan to merge this into the main branch and then revert it?

**Comment by soumyaDghosh** [comment]
> Is the plan to merge this into the main branch and then revert it?

Yup.. In the next update, revert this and delete that additional branch

**Review by adil192 — APPROVED** [review]

**Comment by adil192** [comment]
Btw are you alright with me deleting PR branches after they're merged?

**Comment by soumyaDghosh** [comment]
delete the snap branch only, keep the other one. Wait I have deleted it.

**Pull request merged**
