### PR TITLE
i18n: Update Czech

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
@adil192, do you have some screenshot of it? I'm not sure what exactly it means and have only a little time for this translations (so I don't build it and install it before translating), I'm so sorry for my interruptions.

**Comment by adil192** [comment]
It resets a setting to its default value
image

**Comment by ceskyDJ** [comment]
Thanks for your explanation but I didn't get it. It is for resetting one option in settings or for resetting all options to "factory" state?

**Comment by ceskyDJ** [comment]
Ah, ok. So, I have everything for complete my translation. Thanks.

**Comment by ceskyDJ** [comment]
@adil192, I think it is ready now :D.

**Pull request merged**
