### PR TITLE
workflows: Don't run tests for pull requests with i18n updates

### PR DESCRIPTION
**Pull request by ceskyDJ**
When the pull request changes only files from lib/i18n, tests won't be run.

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Source: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths.

**Comment by ceskyDJ** [comment]
So, maybe there is a way. I use something like that in one of my repositories and it work well for me.

**Comment by adil192** [comment]
Thanks :)

**Review by adil192 — CHANGES_REQUESTED** [review]
Wait is there a way to only turn off the codecov part of the workflow? I use some tests to avoid some common mistakes in translations like spelling Saber as "Sabre"

**Comment by ceskyDJ** [comment]
At least you can divide it into more workflows. There are conditions (ifs), too, but I don't know if it supports this. I'll take a look.

**Comment by ceskyDJ** [comment]
Oh, it isn't supported, as I thought. So, I'd choose one of these ways:
- create two workflows in this case – one for code, one for translations,
- or extract the test you need to run always to its own workflow and use my original example.

**Comment by ceskyDJ** [comment]
As you have it prepared for a manual run, too, I'd prefer the first way. I'll commit an example of my thought.

**Comment by ceskyDJ** [comment]
So, what about something like that? Another option is divide just tests for spelling, etc. to own workflow. You'll need to edit conditions for pull requests (checks required to pass) in Github repository settings.

**Comment by adil192** [comment]
The "Upload to Codecov" requires `flutter test --coverage` to be run first to obtain the coverage information, so this wouldn't work as it is. Creating a separate workflow would work, but this seems like too much work just to hide a comment on PRs so I'm going to close this

**Pull request closed without merging**
