### PR TITLE
i18n: Add Hebrew

### PR DESCRIPTION
**Pull request by Elielv235**
made an hebrew(israel) translation

### CODE REVIEW

**Review by adil192 — CHANGES_REQUESTED** [review]
Thank you!
I've noticed that in your PR and commits, you sometimes use locale code `he` and sometimes use `he_IL`.
`he` would be preferable if there's no significant differences between `he_IL` and other Hebrew locales, like how I use "English" instead of "UK English".
Of course, you're the expert here on Hebrew, so which would you prefer?

**Comment by adil192** [comment]
I'm going to go with just `he` because there are no other sub-locales listed on [the link from the README](https://saimana.com/list-of-country-locale-code/).

**Review by adil192 — APPROVED** [review]

**Comment by adil192** [comment]
Thank you! Would you be interested in being mentioned when there's new strings that need to be translated? https://github.com/adil192/saber/issues/19#issuecomment-1306096416

**Comment by Elielv235** [comment]
yes i do! and there is no difference between he_IL and he cuz IL its just the country code

**Comment by Elielv235** [comment]
and when i will can apply Hebrew into the app itself(because the option isn't showing up)

**Comment by adil192** [comment]
> and when i will can apply Hebrew into the app itself(because the option isn't showing up)

Are you on v0.17.0?

**Pull request merged**
