### PR TITLE
modified display text for lineHeight

### LINKED ISSUE #371: Pick a new name for the line height option
-Pixel 6A
-Android 13
-Version 0.9.2

The default font size is really small, and it would be convenient to just be able to change what the default font size is in layout settings.

### PR DESCRIPTION
**Pull request by hamRS**
Modified the global variable lineHeight with their description

- Closes #371

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Hi, the file you changed is generated, I think editing of `strings.i18n.json` would be better approach.

**Comment by hamRS** [comment]
Mi bad, will change that

**Comment by adil192** [comment]
I feel like this goes to the other extreme of only working for typed notes and not handwritten notes. For handwritten notes, the line height option determines the size of lined backgrounds.

**Comment by ceskyDJ** [comment]
Maybe try the middle way? So, add this second meaning to option description.

**Comment by adil192** [comment]
@ceskyDJ What's your proposal for `"lineHeightDescription"`?

**Comment by ceskyDJ** [comment]
> @ceskyDJ What's your proposal for `"lineHeightDescription"`?

I propose something like "The height of each line (default font size for texts)".

**Comment by ceskyDJ** [comment]
@hamRS, any ideas?

**Comment by adil192** [comment]
Closing this for now

**Pull request closed without merging**
