### PR TITLE
i18n: Update Czech

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
It should be done, but I'd like to check it again (it's too much words where I could have done a mistake). If you hurry a lot, you can merge it, but it is without any quality guarantee (it's about 1.30, so... :D).

**Comment by adil192** [comment]
Please mark this as "Ready for review" when you're ready :)

**Comment by ceskyDJ** [comment]
Of course ;). I'm sorry, I forgot about it a little :D.

**Comment by adil192** [comment]
Don't worry there's no rush

**Comment by ceskyDJ** [comment]
@adil192, anyway, it is ready from my side (after so many changes :D).

**Comment by adil192** [comment]
Thanks!

**Pull request merged**
