### PR TITLE
i18n: Update Czech

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
@adil192, do you have any information about these keys for me?
```
    "settings": {                                                                                                                                                                                                                     
      "prefLabels": {                                                                                                                                                                                                                 
        "editorOpaqueBackgrounds": "Opaque backgrounds"                                                                                                                                                                               
      },                                                                                                                                                                                                                              
      "prefDescriptions": {                                                                                                                                                                                                           
        "editorOpaqueBackgrounds": "Remove transparency from background images and PDFs"                                                                                                                                              
      }                                                                                                                                                                                                                               
    },
```

**Comment by adil192** [comment]
You can see the relevant issue here: https://github.com/adil192/saber/issues/400

**Comment by ceskyDJ** [comment]
@adil192, thanks for linking related issue. I completed Czech translation additions, so feel free to merge it :D.

**Comment by adil192** [comment]
thanks :)

**Pull request merged**
