### PR TITLE
Download images

### PR DESCRIPTION
**Pull request by adil192**

### CODE REVIEW

**Comment by adil192** [comment]
New translation alert @Sdarfeesh @mamasch19 @iamjosuefischer @albanobattistella @jhihyulin @comcloudway
https://github.com/adil192/saber#translating

**Comment by comcloudway** [comment]
Should we translate this as `download` or as `export` - because I'd expect a picture I've imported to say `export`
whilst a linked image should say `download`

**Comment by adil192** [comment]
> Should we translate this as `download` or as `export` - because I'd expect a picture I've imported to say `export` whilst a linked image should say `download`

I prefer "Download" as that's the word that's used in lots of popular apps and also "export" is already used for PDF exporting.

**Comment by albanobattistella** [comment]
> > Should we translate this as `download` or as `export` - because I'd expect a picture I've imported to say `export` whilst a linked image should say `download`
> 
> I prefer "Download" as that's the word that's used in lots of popular apps and also "export" is already used for PDF exporting.

Hi,
for it language "Download".

**Pull request merged**
