### PR TITLE
i18n: Update Czech

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Hi, @adil192! I'm glad you're back and Saber development continues. Anyway, there is one question for this translation. You add a word "fit", so you wanted to change semantics to "How the image on a background is fitting", so how it's positioned, expanded, etc. Is it true?

**Comment by ceskyDJ** [comment]
The Czech translation is something like "Positioning of the background image" now. Maybe something like more like "Adjusting of the background image" will be better. I'll change it.

**Comment by adil192** [comment]
> Hi, @adil192! I'm glad you're back and Saber development continues. Anyway, there is one question for this translation. You add a word "fit", so you wanted to change semantics to "How the image on a background is fitting", so how it's positioned, expanded, etc. Is it true?

Yes that's correct. This corresponds to the existing `boxFit` strings:
https://github.com/adil192/saber/blob/168ef7bdf0a8e2a132f609490d1efefe8efc1be4/lib/i18n/community/strings_cs.i18n.yaml#L256-L259

I will probably still be a little bit inactive until I return to uni (late September) since I'm not taking any notes right now

**Comment by ceskyDJ** [comment]
> I will probably still be a little bit inactive until I return to uni (late September) since I'm not taking any notes right now

I get it. We start already in the mid of September :D. I'm interesting you have pretty enough time for developing open-source in an academic year. I have almost no time after school projects, homework and these things comes.

**Comment by ceskyDJ** [comment]
I'm sorry but I delay merging a bit. I'm not 100% sure about correctness of the translation, so I'll rethink it once more.

**Comment by ceskyDJ** [comment]
I'll try "Layout of the background image" ("Rozložení obrázku na pozadí" in Czech), it sound as the best candidate (at least for now).

**Comment by ceskyDJ** [comment]
So, you can merge it.

**Comment by adil192** [comment]
Thanks!

**Pull request merged**
