### PR TITLE
patterns: add Cornell notes pattern

### PR DESCRIPTION
**Pull request by adil192**
- Loosely related to #553 

image

### CODE REVIEW

**Comment by adil192** [comment]
@akib-89 Please can I have your feedback on a Cornell notes template?
Would you prefer the boxes around each section? And would you prefer each section having a title/subheading?

**Comment by akib-89** [comment]
Yes this looks good to me. But is it possible to provide any process of making this section from the user end not by the template. Template is fine though.

**Comment by adil192** [comment]
> But is it possible to provide any process of making this section from the user end not by the template.

I suppose you'd be able to draw the lines yourself, but why do you ask?

**Comment by akib-89** [comment]
Its completely fine. Thank you.

**Pull request merged**
