### PR TITLE
i18n: Update Czech

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Where the "Theme type" is located? Could you send me screenshot, please? I think it will be quicker than my tries to run some kind of testing version on my own.

**Comment by adil192** [comment]
> Where the "Theme type" is located? Could you send me screenshot, please? I think it will be quicker than my tries to run some kind of testing version on my own.

It's just in the Settings page
image

**Comment by ceskyDJ** [comment]
Thanks. Hmm, It's a little more difficult. What it really changes - only icons or more things?

**Comment by ceskyDJ** [comment]
There is a literal translation, of course, but it is not much understandable, I think.

**Comment by ceskyDJ** [comment]
There are two types of themes (for color scheme and for icon scheme or maybe something else) with one name, aren't they?

**Comment by ceskyDJ** [comment]
So it could be "Color theme" ("Motiv barev") and "Icon theme" ("Motiv ikon") or something like this.

**Comment by adil192** [comment]
It changes a few parts of the UI including icons, dialogues, and input options to their Cupertino equivalents. (or for iOS devices, it lets you change back to the regular style)

**Comment by adil192** [comment]
maybe you could go with something along the lines of changing the target platform for the UI

**Comment by ceskyDJ** [comment]
Ok, so it will be "Color theme" ("Motiv barev") and "UI theme" ("Motiv uživatelského rozhraní") in Czech translation. Is it ok? How could I update translation of older items? Should I change the file with Czech translations?

**Comment by adil192** [comment]
> How could I update translation of older items? Should I change the file with Czech translations?

Yeah that's right

**Comment by adil192** [comment]
I'll mark this as a draft so I don't accidentally merge it

**Comment by ceskyDJ** [comment]
So, I did a little research and update translation to the best version I can produce. So, it's done from my side, feel free to merge it.

There is a conflict, will you solve it or should I have to?

**Comment by adil192** [comment]
Don't worry about conflicts :)

**Pull request merged**
