### PR TITLE
i18n: Update Russian

### PR DESCRIPTION
**Pull request by ShevT**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Nice work! But don't forget to translate app store descriptions (and optionally README, too)! @adil192 updated Saber's description to the final one (before official release), so it needs to be translated, too.

**Comment by ShevT** [comment]
> don't forget to translate app store description (and optionally README, too)! 

How to do it?

**Comment by ceskyDJ** [comment]
It's described in README, see https://github.com/adil192/saber#translating-app-store-descriptions. Is it enough or do you want some more information? In case you need some, let me know. Alternatively see #846 or #843.

**Comment by ceskyDJ** [comment]
@adil192, could you add Flathub description? We could try more languages than just English and Czech, after the content of the Flathub website will be updated.

**Pull request merged**
