### PR TITLE
i18n: Update Czech

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
@adil192, is it really necessary to run Codecov on pull requests, witch only updates community translations? I think it would be better to ignore translations in case of Codecov reports (It's surely configurable in Github Actions, but I didn't check the way you run that).

**Comment by adil192** [comment]
> @adil192, is it really necessary to run Codecov on pull requests, witch only updates community translations? I think it would be better to ignore translations in case of Codecov reports (It's surely configurable in Github Actions, but I didn't check the way you run that).

There's no way (that I know) to distinguish between a PR that changes coverage or not, since even translation PRs sometimes require changes in other files

**Comment by ceskyDJ** [comment]
Hmm, it should be ignored. interesting.
image

**Comment by adil192** [comment]
That's just for what's counted towards the coverage percent, not if codecov comments on a PR

**Comment by ceskyDJ** [comment]
Ok, I see.

**Pull request merged**
