### PR TITLE
i18n: Update Czech

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Is it ok, @adil192?

**Comment by adil192** [comment]
You choose it when you first login to Saber, and it's not related to your Nextcloud account/password.
Please can you update this sentence too?

**Comment by ceskyDJ** [comment]
Of course, this is exactly the reason, why I have asked you for  a check.

**Comment by adil192** [comment]
Thanks!

**Pull request merged**
