### PR TITLE
Update German

### PR DESCRIPTION
**Pull request by comcloudway**

### CODE REVIEW

**Comment by adil192** [comment]
Thank you :)

**Comment by comcloudway** [comment]
Do you know whether I can delete the [patch branches](https://github.com/comcloudway/saber/branches) in my fork?

**Comment by adil192** [comment]
I'm not sure if you're asking how to do so, or if you can, but yes you can and you can do it by pressing the bin icon
image

**Comment by comcloudway** [comment]
Thanks, I know how to, but I wasn't sure if this would break stuff

**Pull request merged**
